const Discord = require('discord.js');

module.exports.run = async (bot, message, args) => {
    let replies = [
        'https://github.com/hayeah/playing-cards-assets/blob/master/png/ace_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/2_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/3_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/4_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/5_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/6_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/7_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/8_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/9_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/10_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/jack_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/queen_of_clubs.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/king_of_clubs.png?raw=true',
        'https://github.com/hayeah/playing-cards-assets/blob/master/png/ace_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/2_of_spades.png?raw=trueSS', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/3_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/4_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/5_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/6_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/7_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/8_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/9_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/10_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/jack_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/queen_of_spades.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/king_of_spades.png?raw=true',
        'https://github.com/hayeah/playing-cards-assets/blob/master/png/ace_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/2_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/3_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/4_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/5_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/6_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/7_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/8_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/9_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/10_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/jack_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/queen_of_hearts.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/king_of_hearts.png?raw=true',
        'https://github.com/hayeah/playing-cards-assets/blob/master/png/ace_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/2_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/3_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/4_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/5_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/6_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/7_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/8_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/9_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/10_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/jack_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/queen_of_diamonds.png?raw=true', 'https://github.com/hayeah/playing-cards-assets/blob/master/png/king_of_diamonds.png?raw=true'
    ]
    let result = Math.floor((Math.random() * replies.length));
    let embed = new Discord.RichEmbed()
    .setColor("#FF000")
    .setDescription("<a:Dots:426956230582599690> Loading the Card, Please Wait.,,,,")
    message.channel.send(embed).then(message => {
    embed.setColor("#000FF")
    embed.setDescription("Heres you're card")
    embed.setImage(replies[result])
    message.edit(embed)
    })
}
module.exports.help = {
    name: "card",
    names: "Card"
}